language: ruby
rvm:
- 2.2.4
- 2.3.0
bundler_args: --jobs=2
script:
  - bundle exec rake db:setup
  - bundle exec rspec spec
cache: bundler
services:
  - postgresql
  - redis-server
addons:
  postgresql: "9.4"
